// ─────────────────────────────────────────
// ANTON HUB — DATA.JS
// Modifier ce fichier pour mettre à jour le programme
// ─────────────────────────────────────────

const ATHLETE = {
  name: 'Anton',
  vma: 14.6, fcMax: 178, fcRepos: 40, poids: 84.4,
  bench3rm: 100, squat3rm: 90, tractions: 8,
};

const ALLURES = [
  { label: 'Z1 Récup',   val: '>6:10',      color: 'green'  },
  { label: 'Z2 Foncier', val: '5:40–6:00',  color: 'green'  },
  { label: 'Seuil',      val: '4:47',        color: 'gold'   },
  { label: 'Cible 10k',  val: '4:30',        color: 'orange' },
  { label: 'VMA 100%',   val: '4:06',        color: 'red'    },
  { label: 'VMA 110%',   val: '3:44',        color: 'red'    },
];

// type: run-easy | run-hard | run-race | swim | muscu-a | muscu-b | muscu-c | rest | race
const WEEKS = [
  { id:'S01', label:'Spécifique 10k — Entrée',  badge:'S7',   startDate:'2026-05-18' },
  { id:'S02', label:'Spécifique 10k — S8',       badge:'S8',   startDate:'2026-05-25' },
  { id:'S03', label:'Spécifique 10k — Pic',      badge:'S9',   startDate:'2026-06-01' },
  { id:'S04', label:'Assimilation + Rappel',      badge:'S10',  startDate:'2026-06-08' },
  { id:'S05', label:'Race Week · 10k Estérel',   badge:'RACE', startDate:'2026-06-15' },
];
const SESSIONS = [

  // ══ S01 · 18 Mai ══
  { id:'s01-lun', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-18', day:'LUN',
    type:'rest', title:'Repos + Mobilité', duration:20,
    main:'1. Rotation thoracique × 10 chaque côté\n2. Hip flexor stretch 60" chaque côté\n3. 90/90 hanches 60"\n4. Rouleau foam : ischios + mollets + IT band\n5. Balle massage plante des pieds',
  },
  { id:'s01-lun-c', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-18', day:'LUN',
    type:'muscu-c', title:'Muscu C · Legs + Abdos · 8h30', duration:25,
    warmup:'5 min mobilité articulaire : chevilles, genoux, hanches',
    table:[
      { ex:'RDL unilatéral KB',     sets:'4 × 8 chaque', load:'KB 24 kg',        rpe:'7/10' },
      { ex:'Step-up KB',            sets:'3 × 10 chaque',load:'KB 24 kg × 2',    rpe:'7/10' },
      { ex:'Nordic curl',           sets:'3 × 6',        load:'Poids corps',     rpe:'8/10' },
      { ex:'Mollet excentrique',    sets:'3 × 12 chaque',load:'Poids corps',     rpe:'7/10' },
      { ex:'Clamshell élastique',   sets:'3 × 15 chaque',load:'Élastique rouge', rpe:'5/10' },
      { ex:'Relevé jambes suspendu',sets:'3 × 10',       load:'Barre + sangles', rpe:'7/10' },
      { ex:'Russian twist',         sets:'3 × 20',       load:'KB 12 kg',        rpe:'6/10' },
    ],
    cooldown:'Étirements ischios + mollets 5 min',
    coachNote:'Legs lundi = jambes fraîches post-repos. Nordic curl RPE 8 = normal, c\'est l\'exercice le plus dur — c\'est voulu.',
  },
  { id:'s01-mar', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-19', day:'MAR',
    type:'run-easy', title:"45' EF + 5 × 10\" sprints", duration:50, volume:'~8km',
    warmup:'8 min trot Z1 (FC <130)\nÉducatifs 2 min : montées genoux + talons-fesses',
    main:'45 min EF @ 5:40–6:00/km · FC 128–148\n\n5 × 10\" sprints dispersés · récup marche 1 min\nDonner tout sur 10 secondes — activation des fibres rapides.',
    cooldown:'Trot 3 min Z1 + étirements mollets + quadriceps',
    recup:'Boule froide mollets si sensation lourde',
    coachNote:'Les sprints de 10" activent les fibres rapides sans fatigue lactique. Échauffez-vous avant chaque sprint.',
  },
  { id:'s01-mer-a', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-20', day:'MER',
    type:'muscu-a', title:'Muscu A · Push + Abdos · 8h30', duration:25,
    warmup:'5 min : rotations épaules + activation pectoraux élastique',
    table:[
      { ex:'Développé couché barre', sets:'4 × 6',         load:'75–80 kg',       rpe:'7/10' },
      { ex:'Dips lestés ceinture',   sets:'3 × 8',         load:'+10–15 kg',      rpe:'7/10' },
      { ex:'Élévations latérales',   sets:'3 × 12',        load:'DB 10 kg',       rpe:'6/10' },
      { ex:'Arnold press DB',        sets:'3 × 10',        load:'DB 17 kg',       rpe:'7/10' },
      { ex:'Pompes prises serrées',  sets:'3 × 12',        load:'Poids corps',    rpe:'6/10' },
      { ex:'Hollow body hold',       sets:'3 × 30"',       load:'—',              rpe:'6/10' },
      { ex:'Ab wheel rollout',       sets:'3 × 10',        load:'Depuis genoux',  rpe:'7/10' },
    ],
    cooldown:'Étirements pectoraux + épaules 3 min',
    coachNote:'Bench à 75–80 kg = ~75% de ton 3RM. Zone force-hypertrophie sans cramer les épaules avant le run.',
  },
  { id:'s01-jeu', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-21', day:'JEU',
    type:'run-hard', title:"⭐ 5 × 6' @ 4:30/km + EF — SÉANCE CLÉ", duration:70, volume:'~11km',
    warmup:"10 min trot Z1 (FC <130)\nÉducatifs 3 min : montées genoux + talons-fesses + jambes tendues\n2 accélérations 30\" progressives vers 4:30/km · récup marche 60\"",
    intervals:[
      { rep:'1–2', dur:"6'", pace:'4:30/km', fc:'162–170', recup:"2'30\" trot" },
      { rep:'3–4', dur:"6'", pace:'4:30/km', fc:'165–173', recup:"2'30\" trot" },
      { rep:'5',   dur:"6'", pace:'4:30/km', fc:'167–175', recup:'—'           },
    ],
    main:"Après les intervalles : 10 min EF @ 5:40/km pour finir",
    cooldown:"5 min trot Z1\nÉtirements : ischios 30\"×2 · mollets excentriques 10 reps · quadriceps 30\"×2",
    recup:'Boule froide quadriceps + mollets · immédiat · 5 min\nBottes presso · 20 min soir',
    coachNote:"5×6' = 30 minutes à allure course. C'est la séance clé de S7. Si tu tiens ça, le sub45 est dans tes jambes.",
  },
  { id:'s01-ven-b', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-22', day:'VEN',
    type:'muscu-b', title:'Muscu B · Pull + Abdos · 8h30', duration:25,
    warmup:'5 min : bandes élastiques épaules + activation dorsaux',
    table:[
      { ex:'Tractions pronation',      sets:'4 × 6',         load:'+5–10 kg ceinture', rpe:'7/10' },
      { ex:'Tirage horizontal TRX',    sets:'3 × 12',        load:'Corps ~45°',        rpe:'6/10' },
      { ex:'Face pull élastique',      sets:'3 × 15',        load:'Élastique rouge',   rpe:'5/10' },
      { ex:'Curl biceps DB',           sets:'3 × 10',        load:'DB 17 kg',          rpe:'7/10' },
      { ex:'Rotation externe allongé', sets:'3 × 15 chaque', load:'DB 5 kg',           rpe:'5/10' },
      { ex:'Pallof press',             sets:'3 × 12 chaque', load:'Élastique violet',  rpe:'6/10' },
      { ex:'Crunch bicycle lent',      sets:'3 × 16',        load:'—',                 rpe:'6/10' },
    ],
    cooldown:'Étirements dorsaux + biceps 3 min',
    coachNote:'Pull vendredi matin avant la nage = timing parfait. Dorsaux et rotateurs épaule activés le matin → meilleur geste crawl cet après-midi.',
  },
  { id:'s01-ven', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-22', day:'VEN',
    type:'swim', title:'Natation — Éducatifs techniques', duration:45,
    warmup:'100m nage libre très lente (zéro tension épaules)\n4 × 25m jambes seules avec planche · récup 20"',
    main:"4 × 25m Catch-up drill\n4 × 25m Breathing drill (respiration tous les 3 coups)\n4 × 50m Nage complète focus placement · récup 30\"\n4 × 25m Finger drag drill",
    cooldown:'100m dos crawlé ou brasse très lente · décompression épaules',
    coachNote:'Phase 1 = 100% technique, zéro cardio. Si tu sors essoufflé → tu es allé trop vite. Voir onglet Nage pour le détail des drills.',
  },
  { id:'s01-sam', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-23', day:'SAM',
    type:'rest', title:'Repos total', duration:0,
    main:'Repos avant la longue de dimanche. Mobilité légère 20 min max si tu veux bouger.',
  },
  { id:'s01-dim', week:'S01', weekLabel:'Spécifique 10k — Entrée', date:'2026-05-24', day:'DIM',
    type:'run-easy', title:"30' EF + 3 × 9' @5:15/km", duration:75, volume:'~12km',
    warmup:"Départ à 6:10/km les 10 premières minutes (FC <130)",
    main:"30 min EF @ 5:40–6:00/km · FC 128–148\n\n3 × 9' @ 5:15/km · récup 3' trot · FC 148–158\n\n10 min EF pour finir",
    cooldown:'Marche 5 min + étirements complets 10 min',
    recup:'Bottes presso · 30 min\nBoule froide mollets\nÉlectrodes Compex récup · 20 min soir',
    coachNote:"Courir cette longue malgré la fatigue des 5×6' de jeudi vous aidera à être plus performant le jour J. Tenez bon.",
  },

  // ══ S02 · 25 Mai ══
  { id:'s02-lun', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-25', day:'LUN',
    type:'rest', title:'Repos + Mobilité', duration:20,
    main:'Mobilité 20 min : rouleau foam + hip flexor + rotation thoracique',
  },
  { id:'s02-lun-c', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-25', day:'LUN',
    type:'muscu-c', title:'Muscu C · Legs + Abdos · 8h30', duration:25,
    warmup:'5 min mobilité articulaire',
    table:[
      { ex:'RDL unilatéral KB',     sets:'4 × 8 chaque', load:'KB 24 kg',        rpe:'7/10' },
      { ex:'Step-up KB',            sets:'4 × 10 chaque',load:'KB 24 kg × 2',    rpe:'7/10' },
      { ex:'Nordic curl',           sets:'3 × 6',        load:'Poids corps',     rpe:'8/10' },
      { ex:'Mollet excentrique',    sets:'3 × 12 chaque',load:'+KB 12 kg',       rpe:'7/10' },
      { ex:'Clamshell élastique',   sets:'3 × 15 chaque',load:'Élastique rouge', rpe:'5/10' },
      { ex:'Relevé jambes suspendu',sets:'3 × 12',       load:'Barre + sangles', rpe:'7/10' },
      { ex:'Russian twist',         sets:'3 × 20',       load:'KB 12 kg',        rpe:'7/10' },
    ],
    cooldown:'Étirements 5 min',
    coachNote:'Progression : Step-up passe à 4 séries. Mollet excentrique avec KB 12 kg.',
  },
  { id:'s02-mar', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-26', day:'MAR',
    type:'run-easy', title:"45' EF — foncier récupération", duration:45, volume:'~7.5km',
    warmup:'5 min trot très léger',
    main:'45 min EF @ 5:40–6:00/km · FC 128–148\nPas de sprints cette semaine — semaine S8 d\'assimilation. Corps qui récupère.',
    cooldown:'Trot 3 min + étirements mollets + quadriceps',
    coachNote:'Semaine S8 du programme = assimilation. Pas de sprints. Profites-en avant le bloc suivant.',
  },
  { id:'s02-mer-a', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-27', day:'MER',
    type:'muscu-a', title:'Muscu A · Push + Abdos · 8h30', duration:25,
    warmup:'5 min activation épaules',
    table:[
      { ex:'Développé couché barre', sets:'4 × 6',   load:'77.5–82.5 kg',   rpe:'7/10' },
      { ex:'Dips lestés ceinture',   sets:'3 × 8',   load:'+12.5–17.5 kg',  rpe:'7/10' },
      { ex:'Élévations latérales',   sets:'3 × 12',  load:'DB 10 kg',       rpe:'6/10' },
      { ex:'Arnold press DB',        sets:'3 × 10',  load:'DB 17 kg',       rpe:'7/10' },
      { ex:'Pompes prises serrées',  sets:'3 × 15',  load:'Poids corps',    rpe:'6/10' },
      { ex:'Hollow body hold',       sets:'3 × 35"', load:'—',              rpe:'7/10' },
      { ex:'Ab wheel rollout',       sets:'3 × 10',  load:'Depuis genoux',  rpe:'7/10' },
    ],
    cooldown:'Étirements pectoraux + épaules 3 min',
    coachNote:'+2.5 kg sur le bench vs S1 si tu étais à RPE 6. Reste à RPE 7 max.',
  },
  { id:'s02-jeu', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-28', day:'JEU',
    type:'run-hard', title:"4 × 2'30\" @ 4:30/km — Rappel allure", duration:45, volume:'~7km',
    warmup:"10 min trot Z1 + éducatifs 3 min + 2 accélérations vers 4:30/km",
    intervals:[
      { rep:'1–4', dur:"2'30\"", pace:'4:30/km', fc:'160–170', recup:"1'15\" trot" },
    ],
    main:"10 min EF @ 5:40/km pour finir",
    cooldown:"5 min trot Z1 + étirements ischios + mollets",
    recup:'Bottes presso · 20 min soir',
    coachNote:"Semaine S8 = fractions courtes intentionnellement. Rappel neuromusculaire de l'allure. Récupérez en marchant ou en footing lent.",
  },
  { id:'s02-ven-b', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-29', day:'VEN',
    type:'muscu-b', title:'Muscu B · Pull + Abdos · 8h30', duration:25,
    warmup:'5 min activation dorsaux + épaules',
    table:[
      { ex:'Tractions pronation',      sets:'4 × 7',         load:'+5–10 kg ceinture', rpe:'7/10' },
      { ex:'Tirage horizontal TRX',    sets:'3 × 12',        load:'Corps ~40°',        rpe:'7/10' },
      { ex:'Face pull élastique',      sets:'3 × 15',        load:'Élastique rouge',   rpe:'5/10' },
      { ex:'Curl biceps DB',           sets:'3 × 10',        load:'DB 17 kg',          rpe:'7/10' },
      { ex:'Rotation externe allongé', sets:'3 × 15 chaque', load:'DB 5 kg',           rpe:'5/10' },
      { ex:'Pallof press',             sets:'3 × 12 chaque', load:'Élastique violet',  rpe:'6/10' },
      { ex:'Crunch bicycle lent',      sets:'3 × 16',        load:'—',                 rpe:'6/10' },
    ],
    cooldown:'Étirements dorsaux 3 min',
    coachNote:'Tractions +1 rep vs S1.',
  },
  { id:'s02-ven', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-29', day:'VEN',
    type:'swim', title:'Natation — Éducatifs + 6×50m allure', duration:45,
    warmup:'200m nage libre décontractée · focus placement',
    main:"4 × 25m éducatifs au choix\n6 × 50m allure confortable soutenue (~75%) · récup 30\"\nFocus : maintenir le geste technique même essoufflé.\n100m nage libre pour finir.",
    cooldown:'100m dos crawlé ou brasse très lente',
  },
  { id:'s02-sam', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-30', day:'SAM',
    type:'rest', title:'Repos total', duration:0,
    main:'Repos avant la longue de dimanche.',
  },
  { id:'s02-dim', week:'S02', weekLabel:'Spécifique 10k — Montée', date:'2026-05-31', day:'DIM',
    type:'run-easy', title:"1h EF — sortie longue douce", duration:60, volume:'~10km',
    warmup:"Départ à 6:10/km les 10 premières minutes",
    main:"1h EF @ 5:40–6:00/km · FC 128–148\nPas de blocs tempo — sortie longue pure.\nRécupérez et profitez-en avant le bloc suivant.",
    cooldown:'Marche 5 min + étirements complets 10 min',
    recup:'Bottes presso · 30 min\nBoule froide mollets',
    coachNote:'S8 = assimilation. Sortie pure sans tempo. Le corps consolide les adaptations.',
  },

  // ══ S03 · 01 Juin ══
  { id:'s03-lun', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-01', day:'LUN',
    type:'rest', title:'Repos + Mobilité', duration:20,
    main:'Mobilité 20 min complète.',
    coachNote:'Semaine de pic — ce lundi est crucial. Repos complet, pas de mobilité intense.',
  },
  { id:'s03-lun-c', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-01', day:'LUN',
    type:'muscu-c', title:'Muscu C · Legs + Abdos · 8h30', duration:25,
    warmup:'5 min mobilité articulaire',
    table:[
      { ex:'RDL unilatéral KB',     sets:'4 × 8 chaque', load:'KB 24 kg',        rpe:'7/10' },
      { ex:'Step-up KB',            sets:'4 × 10 chaque',load:'KB 24 kg × 2',    rpe:'8/10' },
      { ex:'Nordic curl',           sets:'4 × 6',        load:'Poids corps',     rpe:'8/10' },
      { ex:'Mollet excentrique',    sets:'3 × 12 chaque',load:'+KB 12 kg',       rpe:'7/10' },
      { ex:'Clamshell élastique',   sets:'3 × 15 chaque',load:'Élastique rouge', rpe:'5/10' },
      { ex:'Relevé jambes suspendu',sets:'3 × 12',       load:'Barre + sangles', rpe:'8/10' },
      { ex:'Russian twist',         sets:'3 × 20',       load:'KB 16 kg',        rpe:'7/10' },
    ],
    cooldown:'Étirements 5 min',
    coachNote:'Nordic passe à 4 séries. Russian twist passe à KB 16 kg. Dernière semaine chargée avant assimilation S4.',
  },
  { id:'s03-mar', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-02', day:'MAR',
    type:'run-easy', title:"45' EF + 5 × 10\" sprints", duration:50, volume:'~8km',
    warmup:'8 min trot Z1 + éducatifs 2 min',
    main:"45 min EF @ 5:40–6:00/km · FC 128–148\n\n5 × 10\" sprints dispersés · récup marche 1 min\nDonner tout sur 10 secondes — activation des fibres rapides.",
    cooldown:'Trot 3 min + étirements',
    coachNote:'Retour des sprints — S9 repart sur un nouveau bloc. Les fibres rapides se réactivent après la semaine d\'assimilation.',
  },
  { id:'s03-mer-a', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-03', day:'MER',
    type:'muscu-a', title:'Muscu A · Push + Abdos · 8h30', duration:25,
    warmup:'5 min activation épaules',
    table:[
      { ex:'Développé couché barre', sets:'4 × 6',   load:'80–85 kg',      rpe:'7/10' },
      { ex:'Dips lestés ceinture',   sets:'4 × 8',   load:'+15–20 kg',     rpe:'8/10' },
      { ex:'Élévations latérales',   sets:'3 × 12',  load:'DB 12 kg',      rpe:'7/10' },
      { ex:'Arnold press DB',        sets:'3 × 10',  load:'DB 17 kg',      rpe:'7/10' },
      { ex:'Pompes prises serrées',  sets:'3 × 15',  load:'Poids corps',   rpe:'7/10' },
      { ex:'Hollow body hold',       sets:'3 × 40"', load:'—',             rpe:'7/10' },
      { ex:'Ab wheel rollout',       sets:'3 × 12',  load:'Depuis genoux', rpe:'8/10' },
    ],
    cooldown:'Étirements pectoraux + épaules 3 min',
  },
  { id:'s03-jeu', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-04', day:'JEU',
    type:'run-hard', title:"⭐ 4 × 1500m @ 4:30/km — SÉANCE CLÉ", duration:65, volume:'~11km',
    warmup:"10 min trot Z1 + éducatifs 3 min + 2 accélérations vers 4:30/km",
    intervals:[
      { rep:'1',   dur:"1500m", pace:'4:30/km', fc:'162–170', recup:"2' trot" },
      { rep:'2',   dur:"1500m", pace:'4:30/km', fc:'165–172', recup:"2' trot" },
      { rep:'3',   dur:"1500m", pace:'4:30/km', fc:'165–173', recup:"2' trot" },
      { rep:'4',   dur:"1500m", pace:'4:30/km', fc:'167–175', recup:'—'       },
    ],
    main:"10 min EF @ 5:40/km pour finir",
    cooldown:"5 min trot Z1 + étirements complets",
    recup:'Boule froide · immédiat · 5 min\nBottes presso · 30 min\nCompex récup · 20 min soir',
    coachNote:"4×1500m = 27 minutes cumulées à allure course. C'est le premier gros bloc spécifique. Récup en footing lent ou marche.",
  },
  { id:'s03-ven-b', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-05', day:'VEN',
    type:'muscu-b', title:'Muscu B · Pull + Abdos · 8h30', duration:25,
    warmup:'5 min activation dorsaux + épaules',
    table:[
      { ex:'Tractions pronation',      sets:'4 × 8',         load:'+5–10 kg ceinture', rpe:'8/10' },
      { ex:'Tirage horizontal TRX',    sets:'3 × 12',        load:'Corps ~35°',        rpe:'7/10' },
      { ex:'Face pull élastique',      sets:'3 × 15',        load:'Élastique rouge',   rpe:'5/10' },
      { ex:'Curl biceps DB',           sets:'3 × 10',        load:'DB 17 kg',          rpe:'7/10' },
      { ex:'Rotation externe allongé', sets:'3 × 15 chaque', load:'DB 5 kg',           rpe:'5/10' },
      { ex:'Pallof press',             sets:'3 × 12 chaque', load:'Élastique violet',  rpe:'7/10' },
      { ex:'Crunch bicycle lent',      sets:'3 × 20',        load:'—',                 rpe:'7/10' },
    ],
    cooldown:'Étirements dorsaux 3 min',
    coachNote:'Tractions 4×8 — pic du bloc. Épaules OK après les 5×6 de jeudi ?',
  },
  { id:'s03-ven', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-05', day:'VEN',
    type:'swim', title:'Natation — Test 800m continu', duration:50,
    warmup:'200m nage libre décontractée',
    main:"4 × 25m éducatifs au choix\n\n800m continu → NOTER LE TEMPS ET LES SENSATIONS\nAllure confortable — première mesure de référence pour le Bloc 2.\n\n4 × 25m technique pour finir",
    cooldown:'100m brasse légère',
    coachNote:'Note perso : _____ min _____ sec · Nombre d\'arrêts : _____',
  },
  { id:'s03-sam', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-06', day:'SAM',
    type:'rest', title:'Repos total', duration:0,
    main:'Après la semaine la plus chargée du Bloc 1 — repos complet.',
  },
  { id:'s03-dim', week:'S03', weekLabel:'Spécifique 10k — Pic', date:'2026-06-07', day:'DIM',
    type:'run-easy', title:"50' EF + progression finale", duration:80, volume:'~13km',
    warmup:"Départ à 6:10/km les 10 premières minutes",
    main:"30 min EF @ 5:40–6:00/km\n\nProgression finale :\n5' @ 5:30/km · récup 1' trot\n5' @ 5:00/km · récup 1' trot\n5' @ 4:30/km\n\n10 min EF pour finir",
    cooldown:'Marche 5 min + étirements complets 10 min',
    recup:'Bottes presso · 30–40 min\nBoule froide mollets\nPistolet massage quadriceps',
    coachNote:"La progression finale simule la montée en régime d'une course. Les 5' à 4:30/km en fin de longue = préparation mentale et physique au jour J.",
  },

  // ══ S04 · 08 Juin ══
  { id:'s04-lun', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-08', day:'LUN',
    type:'rest', title:'Repos total', duration:0,
    main:'Semaine d\'assimilation. Volume réduit — les adaptations des 3 semaines précédentes se consolident.',
    coachNote:'Ne pas sauter cette semaine. C\'est ici que le corps s\'adapte vraiment.',
  },
  { id:'s04-lun-c', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-08', day:'LUN',
    type:'muscu-c', title:'Muscu C · Legs allégé · 8h30', duration:20,
    warmup:'5 min mobilité articulaire',
    table:[
      { ex:'RDL unilatéral KB',     sets:'3 × 8 chaque', load:'KB 24 kg',        rpe:'6/10' },
      { ex:'Step-up KB',            sets:'3 × 8 chaque', load:'KB 24 kg × 2',    rpe:'6/10' },
      { ex:'Nordic curl',           sets:'2 × 6',        load:'Poids corps',     rpe:'7/10' },
      { ex:'Mollet excentrique',    sets:'3 × 10 chaque',load:'Poids corps',     rpe:'6/10' },
      { ex:'Relevé jambes suspendu',sets:'3 × 10',       load:'Barre + sangles', rpe:'6/10' },
      { ex:'Russian twist',         sets:'3 × 16',       load:'KB 12 kg',        rpe:'6/10' },
    ],
    cooldown:'Étirements 5 min',
    coachNote:'Volume -30%, RPE 6 max. Le corps assimile.',
  },
  { id:'s04-mar', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-09', day:'MAR',
    type:'run-easy', title:"45' EF + 5 × 10\" sprints", duration:50, volume:'~8km',
    warmup:'8 min trot Z1 + éducatifs 2 min',
    main:"45 min EF @ 5:40–6:00/km · FC 128–148\n\n5 × 10\" sprints dispersés · récup marche 1 min\n100% effort sur chaque sprint.",
    cooldown:'Trot 3 min + étirements',
    coachNote:'S10 = dernier bloc avant race week. Sprints de retour pour maintenir le tonus neuromusculaire.',
  },
  { id:'s04-mer-a', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-10', day:'MER',
    type:'muscu-a', title:'Muscu A · Push allégé · 8h30', duration:20,
    warmup:'5 min activation épaules',
    table:[
      { ex:'Développé couché barre', sets:'3 × 6',   load:'75 kg',         rpe:'6/10' },
      { ex:'Dips lestés',            sets:'3 × 8',   load:'+10 kg',        rpe:'6/10' },
      { ex:'Élévations latérales',   sets:'3 × 12',  load:'DB 10 kg',      rpe:'6/10' },
      { ex:'Arnold press DB',        sets:'3 × 10',  load:'DB 15 kg',      rpe:'6/10' },
      { ex:'Hollow body hold',       sets:'3 × 30"', load:'—',             rpe:'6/10' },
      { ex:'Ab wheel rollout',       sets:'3 × 8',   load:'Depuis genoux', rpe:'6/10' },
    ],
    cooldown:'Étirements 3 min',
  },
  { id:'s04-jeu', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-11', day:'JEU',
    type:'run-hard', title:"⭐ 4 × 8' @ 4:30/km — SÉANCE CLÉ", duration:70, volume:'~12km',
    warmup:"10 min trot Z1 + éducatifs 3 min + 2 accélérations vers 4:30/km",
    intervals:[
      { rep:'1',   dur:"8'", pace:'4:30/km', fc:'162–170', recup:"2' trot" },
      { rep:'2',   dur:"8'", pace:'4:30/km', fc:'165–172', recup:"2' trot" },
      { rep:'3',   dur:"8'", pace:'4:30/km', fc:'165–173', recup:"2' trot" },
      { rep:'4',   dur:"8'", pace:'4:30/km', fc:'167–175', recup:'—'       },
    ],
    main:"10 min EF @ 5:40/km pour finir",
    cooldown:"5 min trot Z1 + étirements complets",
    recup:'Boule froide · immédiat · 5 min\nBottes presso · 30 min\nCompex récup · 20 min soir',
    coachNote:"4×8' = 32 minutes cumulées à allure course. Si vous réussissez cette séance, vous pouvez être confiant pour le sub45 le jour J.",
  },
  { id:'s04-ven-b', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-12', day:'VEN',
    type:'muscu-b', title:'Muscu B · Pull allégé · 8h30', duration:20,
    warmup:'5 min activation dorsaux',
    table:[
      { ex:'Tractions pronation',      sets:'3 × 6',         load:'+5 kg ceinture',  rpe:'6/10' },
      { ex:'Tirage horizontal TRX',    sets:'3 × 10',        load:'Corps ~45°',      rpe:'6/10' },
      { ex:'Face pull élastique',      sets:'3 × 15',        load:'Élastique rouge', rpe:'5/10' },
      { ex:'Curl biceps DB',           sets:'3 × 10',        load:'DB 15 kg',        rpe:'6/10' },
      { ex:'Rotation externe allongé', sets:'3 × 12 chaque', load:'DB 5 kg',         rpe:'5/10' },
      { ex:'Pallof press',             sets:'3 × 10 chaque', load:'Élastique orange',rpe:'5/10' },
      { ex:'Crunch bicycle lent',      sets:'3 × 14',        load:'—',               rpe:'5/10' },
    ],
    cooldown:'Étirements dorsaux 3 min',
  },
  { id:'s04-ven', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-12', day:'VEN',
    type:'swim', title:'Natation — 6×100m continuité', duration:45,
    warmup:'4 × 25m éducatifs',
    main:'6 × 100m @ allure confortable · récup 45"\nPremière fois à 100m — maintenir technique sur la longueur.',
    cooldown:'100m brasse légère',
  },
  { id:'s04-sam', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-13', day:'SAM',
    type:'rest', title:'Repos total', duration:0,
    main:'Repos avant la longue douce de dimanche.',
  },
  { id:'s04-dim', week:'S04', weekLabel:'Assimilation + Rappel', date:'2026-06-14', day:'DIM',
    type:'run-easy', title:"50' EF + 20' progressif 5:30→4:30/km", duration:80, volume:'~13km',
    warmup:"Départ à 6:10/km les 10 premières minutes",
    main:"30 min EF @ 5:40–6:00/km · FC 128–148\n\n20 min progression douce :\nDépart @ 5:30/km → accélération progressive vers 4:30/km sur 20 min\n\n10 min EF pour finir",
    cooldown:'Marche 5 min + étirements complets 10 min',
    recup:'Bottes presso · 30 min\nCompex récup · soir',
    coachNote:"La progression de 5:30 vers 4:30 sur 20 min simule la montée en régime de la course. Dernière longue avant race week — profites-en.",
  },

  // ══ S05 · 15 Juin · RACE WEEK ══
  { id:'s05-lun', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-15', day:'LUN',
    type:'rest', title:'Repos total', duration:0,
    main:'Ton corps est entraîné. Cette semaine tu ne gagnes plus de condition — tu la conserves.',
    coachNote:'Pas de muscu cette semaine.',
  },
  { id:'s05-mar', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-16', day:'MAR',
    type:'run-easy', title:"45' EF — activation légère", duration:45, volume:'~7.5km',
    main:"45 min EF @ 5:40–6:00/km\nPas de sprints. Foncier pur. Jambes actives sans stress.",
  },
  { id:'s05-mer', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-17', day:'MER',
    type:'rest', title:'Repos', duration:0,
    main:'Repos.',
  },
  { id:'s05-jeu', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-18', day:'JEU',
    type:'run-hard', title:"5 × 1' @ 4:30/km — Rappel neuro", duration:40, volume:'~6km',
    warmup:"10 min trot Z1 + éducatifs + 2 accélérations",
    intervals:[
      { rep:'1–5', dur:"1'", pace:'4:30/km', fc:'160–170', recup:"1' trot" },
    ],
    main:"10 min EF pour finir",
    cooldown:"Étirements légers 5 min",
    coachNote:'Tapis : 13.3 km/h. Très court intentionnellement. Le système nerveux se souvient de l\'allure. Décontracté — c\'est un rappel, pas un effort.',
  },
  { id:'s05-ven', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-19', day:'VEN',
    type:'rest', title:'Repos — Nutrition + Mental', duration:0,
    main:"Charge glucides : pâtes · riz · pain · hydratation continue.",
    coachNote:"Mental : Tu as fait le travail. En 4 semaines tu es passé de 5×4' à 5×6' à 4:30/km. Le jour J tu as l'adrénaline en plus. C'est réel.",
  },
  { id:'s05-sam', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-20', day:'SAM',
    type:'rest', title:'Marche 20\' + mobilité', duration:30,
    main:'20 min marche légère · mobilité douce 10 min · check matériel',
    recup:'Bottes presso optionnel 20 min',
  },
  { id:'s05-dim', week:'S05', weekLabel:'Race Week · 10k Estérel', date:'2026-06-21', day:'DIM',
    type:'race', title:'🏁 10k ESTÉREL — TARGET SUB 45:00', duration:45, volume:'10km',
    warmup:"15 min avant le départ :\n10 min trot très léger + éducatifs 3 min + 2 accélérations vers allure course",
    main:"km 1 → 4:35/km MAX\nL'adrénaline pousse à partir trop vite → résiste. km 1 trop rapide = km 7–10 en enfer.\n\nkm 2–7 → 4:30/km verrouillé\nAllure mécanique. Pas d'émotion. Respire. Gère.\n\nkm 8–9 → Donne plus\nkm 10 → Vide les batteries complètement",
    cooldown:'Marche 10 min immédiatement après l\'arrivée\nÉtirements légers',
    recup:'Bottes presso · 40 min\nCompex récup · 30 min soir',
  },

  // ══ BLOC 2 + 3 — Placeholders ══
  { id:'b2-placeholder', week:'B2', weekLabel:'Triathlon S', date:'2026-06-22', day:'',
    type:'rest', title:'Bloc 2 — Triathlon S · À venir', duration:0,
    main:'22 Juin → 19 Sept 2026 · 13 semaines\n\nCe bloc sera construit après le 10k du 21 Juin.\n\nArchitecture 3+1 · Nage 2×/sem · Bike erg · Briques · Affûtage 2 semaines avant.',
  },
  { id:'b3-placeholder', week:'B3', weekLabel:'Hyrox Double Men', date:'2026-09-20', day:'',
    type:'rest', title:'Bloc 3 — Hyrox Double Men · À venir', duration:0,
    main:'20 Sept → 28 Oct 2026 · 5 semaines\n\nConstruit après le Triathlon S.\n\nSki Erg · Row · Wall Ball · Sled · Burpees · Sandbag · Circuits run/work · Stratégie Double Men.',
  },
];

// ─────────────────────────────────────────
// MUSCU REFERENCE
// ─────────────────────────────────────────
const MUSCU_ROUTINES = [
  {
    id: 'routine-a',
    title: 'Routine A — Push',
    sub: 'Pectoraux · Épaules · Triceps + Abdos · Mercredi 8h30',
    color: 'orange',
    exercises: [
      { name:'Développé couché barre',   sets:'4 × 6',   load:'75–85 kg (prog.)',      rpe:'7/10', muscle:'Pectoraux, triceps, deltoïdes ant.',    transfer:'Posture run, puissance bras nage' },
      { name:'Dips lestés ceinture',     sets:'3–4 × 8', load:'+10–20 kg (prog.)',     rpe:'7–8/10', muscle:'Pectoraux bas, triceps',             transfer:'Force de poussée fonctionnelle' },
      { name:'Élévations latérales DB',  sets:'3 × 12',  load:'DB 10–12 kg',           rpe:'6/10', muscle:'Deltoïdes latéraux',                   transfer:'Stabilité épaule en nage' },
      { name:'Arnold press DB',          sets:'3 × 10',  load:'DB 17 kg',              rpe:'7/10', muscle:'Deltoïdes complet',                    transfer:'Force overhead, stabilité' },
      { name:'Pompes prises serrées',    sets:'3 × 12–15', load:'Poids corps',         rpe:'6–7/10', muscle:'Triceps, pectoraux internes',        transfer:'Endurance musculaire haut du corps' },
      { name:'Hollow body hold',         sets:'3 × 30–40"', load:'—',                  rpe:'6–7/10', muscle:'Core transverse, abdos',            transfer:'Stabilité tronc en foulée' },
      { name:'Ab wheel rollout',         sets:'3 × 8–12', load:'Depuis genoux',        rpe:'7–8/10', muscle:'Core profond, abdos',               transfer:'Force excentrique core, transfert run' },
    ],
  },
  {
    id: 'routine-b',
    title: 'Routine B — Pull',
    sub: 'Dorsaux · Biceps · Rotateurs + Abdos · Vendredi 8h30',
    color: 'blue',
    exercises: [
      { name:'Tractions pronation',       sets:'4 × 6–8',       load:'+5–10 kg ceinture', rpe:'7–8/10', muscle:'Grand dorsal, biceps, rhomboïdes', transfer:'Traction aquatique crawl directe' },
      { name:'Tirage horizontal TRX',     sets:'3 × 12',         load:'Corps 35–45°',      rpe:'6–7/10', muscle:'Dorsaux moyens, rhomboïdes',      transfer:'Posture run, traction nage' },
      { name:'Face pull élastique',       sets:'3 × 15',         load:'Élastique rouge',   rpe:'5/10',   muscle:'Rotateurs ext. épaule, trapèze',  transfer:'Prévention blessure épaule nage' },
      { name:'Curl biceps DB',            sets:'3 × 10',         load:'DB 17 kg',          rpe:'7/10',   muscle:'Biceps, brachial',                transfer:'Esthétique + force traction' },
      { name:'Rotation externe allongé',  sets:'3 × 15 chaque',  load:'DB 5 kg',           rpe:'5/10',   muscle:'Infra-épineux, petit rond',       transfer:'Santé épaule, entrée de main propre' },
      { name:'Pallof press',              sets:'3 × 12 chaque',  load:'Élastique violet',  rpe:'6–7/10', muscle:'Obliques, anti-rotation',         transfer:'Stabilité latérale foulée et nage' },
      { name:'Crunch bicycle lent',       sets:'3 × 16–20',      load:'—',                 rpe:'6–7/10', muscle:'Obliques, droit abdominal',       transfer:'Rotation de hanches en crawl' },
    ],
  },
  {
    id: 'routine-c',
    title: 'Routine C — Legs',
    sub: 'Ischios · Fessiers · Stabilisation + Abdos · Lundi 8h30',
    color: 'lime',
    exercises: [
      { name:'RDL unilatéral KB',      sets:'4 × 8 chaque',  load:'KB 24 kg',        rpe:'7/10',   muscle:'Ischios, fessiers, stabilisateurs',  transfer:'Chaîne postérieure propulsion run' },
      { name:'Step-up KB',             sets:'3–4 × 10 chaque', load:'KB 24 kg × 2',  rpe:'7–8/10', muscle:'Quadriceps, fessiers',               transfer:'Force d\'impulsion dynamique' },
      { name:'Nordic curl',            sets:'3–4 × 6',        load:'Poids corps',    rpe:'8/10',   muscle:'Ischios excentriques',               transfer:'Prévention claquage ischio' },
      { name:'Mollet excentrique',     sets:'3 × 10–12 chaque', load:'PC → +KB 12',  rpe:'7/10',   muscle:'Soléaire, gastrocnémien',           transfer:'Prévention tendinite Achille' },
      { name:'Clamshell élastique',    sets:'3 × 15 chaque',  load:'Élastique rouge', rpe:'5/10',  muscle:'Rotateurs ext. hanche, moyen fessier', transfer:'Stabilité genou en appui' },
      { name:'Relevé jambes suspendu', sets:'3 × 10–12',      load:'Barre + sangles', rpe:'7–8/10', muscle:'Abdos bas, hip flexors',            transfer:'Levée de genou run, force core bas' },
      { name:'Russian twist',          sets:'3 × 20',         load:'KB 12–16 kg',    rpe:'6–7/10', muscle:'Obliques rotatifs',                  transfer:'Rotation spécifique Hyrox/nage' },
    ],
  },
];

// ─────────────────────────────────────────
// SWIM DRILLS
// ─────────────────────────────────────────
const SWIM_DRILLS = [
  { num:'01', name:'Catch-up drill',            vol:'4 × 25m · récup 20"',
    exec:'Un bras ne part pas tant que l\'autre n\'a pas rejoint l\'épaule avant.',
    focus:'Allonger la distance par cycle · réduire la traînée',
    error:'Partir trop vite avec le bras suivant annule l\'effet' },
  { num:'02', name:'Breathing drill',           vol:'4 × 50m · récup 30"',
    exec:'Expire entièrement sous l\'eau. Inspire en rotation latérale en rasant la surface. Alterne côté tous les 3 coups.',
    focus:'Décontaminer la peur de manquer d\'air · équilibrer la rotation',
    error:'Lever la tête en avant pour inspirer fait couler les jambes' },
  { num:'03', name:'Finger drag drill',         vol:'4 × 25m · récup 20"',
    exec:'En sortant le bras, maintiens les doigts en contact avec la surface jusqu\'à l\'entrée suivante. Coude haut obligatoire.',
    focus:'Corriger l\'entrée de main · éviter les éclaboussures',
    error:'Coude bas lors du retour' },
  { num:'04', name:'Kick drill · Jambes planche', vol:'4 × 25m · récup 20"',
    exec:'Planche devant, battement continu depuis les hanches. Chevilles souples, amplitude faible.',
    focus:'Propulsion jambes + position horizontale',
    error:'Plier les genoux : le battement doit venir des hanches' },
  { num:'05', name:'Single arm drill',          vol:'4 × 25m chaque côté · récup 30"',
    exec:'Un seul bras nage, l\'autre tendu devant. Respire du côté du bras actif.',
    focus:'Traction et rotation de hanche sur chaque côté',
    error:'Bloquer la rotation — c\'est le but du drill' },
  { num:'06', name:'Fist drill',               vol:'4 × 50m alternés poings/mains',
    exec:'Nage avec les poings fermés. Le corps compense avec l\'avant-bras. Alterne 25m poings / 25m ouvert.',
    focus:'Prise d\'eau de l\'avant-bras complet',
    error:'Ralentir est normal et utile avec les poings' },
  { num:'07', name:'Side kick drill',          vol:'4 × 25m chaque côté · récup 30"',
    exec:'Couché sur le côté, un bras tendu devant, battement continu en position de rotation.',
    focus:'Équilibre en rotation latérale · position de moindre résistance',
    error:'Utiliser le battement pour rester horizontal' },
];
